name: Nightly build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "DATE=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
      
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: llvm/llvm-project
          path: llvm-project

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Configure LLVM
        run: cd llvm-project && ../x.sh configure

      - name: Build LLVM
        run: cd llvm-project && ../x.sh build

      - name: Package LLVM
        run: |
          cd llvm-project && tar -czvf llvm-m68k-nightly.tar.gz llvm-m68k-nightly

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: llvm-m68k-nightly
          path: llvm-project/llvm-m68k-nightly.tar.gz
          retention-days: 3

