name: llvm-m68k build

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: LLVM version
        required: true
        default: 22.1.3
      release_tag:
        description: Release tag
        required: true
        default: llvm-m68k-22.1.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Download LLVM
        run: |
          wget https://github.com/llvm/llvm-project/releases/download/llvmorg-${{ inputs.version }}/llvm-project-${{ inputs.version }}.src.tar.xz
          tar -xJf llvm-project-${{ inputs.version }}.src.tar.xz
          mv llvm-project-${{ inputs.version }}.src llvm-project

      - name: Build LLVM
        run: |
          cd llvm-project

          cmake \
              -G Ninja \
              -S llvm \
              -B build \
              -D CMAKE_INSTALL_PREFIX=llvm-m68k \
              -D CMAKE_BUILD_TYPE="Release" \
              -D CMAKE_C_COMPILER=clang \
              -D CMAKE_CXX_COMPILER=clang++ \
              -D LLVM_CCACHE_BUILD=ON \
              -D LLVM_ENABLE_PROJECTS="clang" \
              -D LLVM_ENABLE_RUNTIMES="" \
              -D LLVM_ENABLE_LLD=ON \
              -D LLVM_BUILD_LLVM_DYLIB=ON \
              -D LLVM_LINK_LLVM_DYLIB=ON \
              -D CLANG_LINK_CLANG_DYLIB=ON \
              -D LLVM_TARGETS_TO_BUILD="X86" \
              -D LLVM_EXPERIMENTAL_TARGETS_TO_BUILD="M68k" \
              -D LLVM_INSTALL_TOOLCHAIN_ONLY=ON

          ninja -C build -j $(nproc --all)

      - name: Package LLVM
        run: |
          cd llvm-project
          ninja -C build install/strip
          tar -C llvm-m68k -cf - . | zstd -c -T0 --ultra -20 -o llvm-m68k.tar.zst

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.release_tag }}
          files: llvm-project/llvm-m68k.tar.zst
